include:
  - ./eureka-server/docker-compose.yml
  - ./api-gateway/docker-compose.yml
  - ./user-service/docker-compose.yaml
  - ./trip-service/docker-compose.yml
  - ./infrastructure/docker-compose.yml
networks:
  app-network:
    driver: bridge
