server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${CLIENT_URL}
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
            - id: trip-service
              uri: lb://trip-service
              predicates:
                - Path=/trip-service/**
            - id: driver-service
              uri: lb://driver-service
              predicates:
                - Path=/driver-service/**

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: trip-service
        url: /trip-service/v3/api-docs
      - name: driver-service
        url: /driver-service/v3/api-docs