server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${CLIENT_URL:http://discovery-server:8761/eureka/}
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
            - id: trip-service
              uri: lb://trip-service
              predicates:
                - Path=/trip-service/**
            - id: driver-service
              uri: lb://driver-service
              predicates:
                - Path=/driver-service/**

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: trip-service
        url: /trip-service/v3/api-docs
      - name: driver-service
        url: /driver-service/v3/api-docs

jwt:
  public-key: ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyVNBqfD1Ia48pRPIJ0Ji 3lvwFb+d64Jeb5hbQA2vY5RcOpuH6lPXom4/ESMP0dj2Vg345uU79GCvMEEBFqyh k3HtCPS/0maPQ/VZIEtxr5+4lw0K67KXgF1/2GydFSkiWUQ2rdzbQ8DfMpLxvbjg YDoRgdWBNtvR/eHPCXIfgynl/GjI8Wgougi4BgskpFxmdF8celPJkLN/0xqzCQch 8ZC0L3VVzMhyvMCVHAHrxnL6ELApPdOjLOsmR+BeXj8saiKXl+zIT56NkBdFzVZh lAq+2j5gdnb1iwS7cmYK9JWNRtVctMWY+fbxCxRRO3tdgJGwwo9nLkhKeg3epkLg YwIDAQAB -----END PUBLIC KEY-----}
