server:
  port: 8002
  servlet:
    context-path: /driver-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${CLIENT_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD}
      database: 0
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.HashMap
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


    bootstrap-servers: localhost:9092

app:
  driver-search-max-count:10