server:
  port: 8083
  servlet:
    context-path: /driver-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  data:
    redis:
      host: redis-driver-db
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0
app:
  driver-search-max-count:10
