# File: cd-api-gateway.yml

name: CD - API Gateway

on:
  workflow_run:
    workflows: ["CI - API Gateway"]
    types:
      - completed
    branches:
      - test/CD
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "uit-go-gateway-service"
          # Lấy SHA của commit đã kích hoạt workflow CI
          images: "${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.event.workflow_run.head_sha }}"