name: CI - API Gateway

on:
  push:
    branches:
      - main
      - develop
      - test/CD
    paths:
      - 'api-gateway/**'
      - '.github/workflows/ci-api-gateway.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'api-gateway/**'
  workflow_dispatch:


jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      working-directory: api-gateway
      run: chmod +x gradlew

    - name: Install dependencies
      working-directory: api-gateway
      run: ./gradlew clean build -x test --no-daemon

    - name: Run unit tests
      working-directory: api-gateway
      run: ./gradlew test --no-daemon

    - name: Build Docker Image
      working-directory: api-gateway
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }} .

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      working-directory: api-gateway
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}

    # Optional: Upload build artifact
    # - name: Upload build artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: api-gateway-jar
    #     path: api-gateway/build/libs/*.jar



