name: CI - Driver Service

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'driver-service/**'
      - '.github/workflows/ci-driver-service.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'driver-service/**'

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      working-directory: driver-service
      run: chmod +x gradlew

    - name: Install dependencies
      working-directory: driver-service
      run: ./gradlew clean build -x test --no-daemon

    # - name: Run unit tests
    #   working-directory: driver-service
    #   run: ./gradlew test --no-daemon

    - name: Build Docker Image
      working-directory: driver-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/driver-service:${{ github.sha }} .

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      working-directory: driver-service
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/driver-service:${{ github.sha }}

    # Optional: Upload build artifact
    # - name: Upload build artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: driver-service-jar
    #     path: driver-service/build/libs/*.jar
